import { mkdir, rm, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { formatTimeline, runSimulation } from "./simulator";

function options(argv:string[]) { const out:Record<string,string|boolean>={}; for(let i=0;i<argv.length;i++){const arg=argv[i];if(!arg.startsWith("--"))throw new Error(`Unexpected argument: ${arg}`);const key=arg.slice(2);if(key==="verbose"){out[key]=true;continue;}const value=argv[++i];if(!value||value.startsWith("--"))throw new Error(`Missing value for --${key}`);out[key]=value;}return out; }
function positive(value:string|boolean|undefined,name:string,defaultValue:number){const n=value===undefined?defaultValue:Number(value);if(!Number.isInteger(n)||(name!=="seed"&&n<1))throw new Error(`--${name} must be ${name==="seed"?"an integer":"a positive integer"}`);return n;}
const inr=(paise:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(paise/100);

async function main(){
  const args=options(process.argv.slice(2)); const allowed=new Set(["cases","days","seed","strategy","scenario","output","verbose","case"]);for(const k of Object.keys(args))if(!allowed.has(k))throw new Error(`Unknown option --${k}`);
  if(args.strategy!==undefined&&args.strategy!=="baseline")throw new Error("Only --strategy baseline is currently supported");if(args.scenario!==undefined&&args.scenario!=="standard")throw new Error("Only --scenario standard is currently supported");
  const result=runSimulation({caseCount:positive(args.cases,"cases",1000),days:positive(args.days,"days",30),seed:positive(args.seed,"seed",42)}); const root=resolve(String(args.output??"simulation-results"));const dir=resolve(root,`run-${result.runId}`);if(!dir.startsWith(root+"/")&&dir!==root)throw new Error("Invalid output path");await rm(dir,{recursive:true,force:true});await mkdir(dir,{recursive:true});
  const json=(value:unknown)=>JSON.stringify(value,null,2)+"\n"; await Promise.all([writeFile(`${dir}/config.json`,json({simulatorVersion:"1.0.0",logicalRunId:result.runId,...result.config,provenance:"SYNTHETIC_SIMULATION"})),writeFile(`${dir}/portfolio.json`,json(result.initialPortfolio)),writeFile(`${dir}/simulation-state.json`,json({warning:"HIDDEN SYNTHETIC ENVIRONMENT — NEVER PROVIDED TO STRATEGIES",customers:result.hiddenState})),writeFile(`${dir}/cases-final.json`,json(result.finalCases)),writeFile(`${dir}/audit-events.jsonl`,result.auditEvents.map(e=>JSON.stringify(e)).join("\n")+"\n"),writeFile(`${dir}/metrics.json`,json(result.metrics)),writeFile(`${dir}/summary.md`,summary(result))]);
  console.log(`Synthetic simulation ${result.runId}\nCases generated: ${result.config.caseCount}\nVirtual days: ${result.config.days}\nStarting amount: ${inr(result.metrics.portfolio.totalStartingOutstandingPaise)}\nRecovered amount: ${inr(result.metrics.recovery.totalRecoveredPaise)}\nRecovery rate: ${(result.metrics.recovery.recoveryRate*100).toFixed(2)}%\nFull / partial recoveries: ${result.metrics.recovery.fullyRecoveredCases} / ${result.metrics.recovery.partiallyRecoveredCases}\nPromises fulfilled: ${result.metrics.promises.fulfilled}\nEscalations: ${result.metrics.recovery.escalatedCases}\nPolicy blocks: ${result.metrics.safety.policyBlocks}\nArtifacts: ${dir}`);if(args.case)console.log("\n"+formatTimeline(result,String(args.case)));if(args.verbose)console.log("\n"+formatTimeline(result,result.finalCases[0].id));
}
function summary(r:ReturnType<typeof runSimulation>){return `# Synthetic recovery benchmark\n\n**Simulation outcomes are synthetic and are not claims about actual Razorpay merchant recovery performance.**\n\n- Logical run: \`${r.runId}\`\n- Seed: ${r.config.seed}\n- Cases / virtual days: ${r.config.caseCount} / ${r.config.days}\n- Starting outstanding: ${inr(r.metrics.portfolio.totalStartingOutstandingPaise)}\n- Simulated recovery: ${inr(r.metrics.recovery.totalRecoveredPaise)} (${(r.metrics.recovery.recoveryRate*100).toFixed(2)}%)\n- Fully / partially recovered: ${r.metrics.recovery.fullyRecoveredCases} / ${r.metrics.recovery.partiallyRecoveredCases}\n- Disputed / escalated: ${r.metrics.recovery.disputedCases} / ${r.metrics.recovery.escalatedCases}\n- Reconciliation valid: ${r.metrics.reconciliation.valid}\n\nReceivables, behavior, promises, disputes, and payments in this report are synthetic. Razorpay Test Mode is not called by this harness.\n`;}
main().catch(e=>{console.error(e instanceof Error?e.message:e);process.exitCode=1;});
