import { describe, expect, test } from "bun:test";
import { keyedUnit } from "../src/simulation/random";
import { BaselineStrategy, DEFAULT_CONFIG, evaluatePolicy, generatePortfolio, projectObservable, runSimulation } from "../src/simulation/simulator";
import type { SimulationCase } from "../src/simulation/types";

describe("deterministic recovery simulation",()=>{
  test("portfolio is deterministic, varied by seed, and valid",()=>{const a=generatePortfolio({...DEFAULT_CONFIG,caseCount:40});const b=generatePortfolio({...DEFAULT_CONFIG,caseCount:40});const c=generatePortfolio({...DEFAULT_CONFIG,caseCount:40,seed:43});expect(a).toEqual(b);expect(a).not.toEqual(c);for(const x of a.cases){expect(x.outstandingPaise+x.recoveredPaise).toBe(x.originalAmountPaise);expect(x.outstandingPaise).toBeGreaterThanOrEqual(0);}});
  test("full runs reproduce cases, events, and metrics",()=>{const config={caseCount:30,days:15,seed:91};const a=runSimulation(config),b=runSimulation(config);expect(a.finalCases).toEqual(b.finalCases);expect(a.auditEvents).toEqual(b.auditEvents);expect(a.metrics).toEqual(b.metrics);expect(a.metrics.reconciliation.valid).toBe(true);});
  test("observable projection excludes latent traits",()=>{const generated=generatePortfolio({...DEFAULT_CONFIG,caseCount:1});const context=projectObservable(generated.cases[0],0) as unknown as Record<string,unknown>;for(const key of ["profile","responsiveness","paymentAbility","willingness","disputePropensity","promiseReliability","partialTendency","spontaneousPayment"])expect(key in context).toBe(false);expect(new BaselineStrategy().decide(projectObservable(generated.cases[0],0)).action).toBeString();});
  test("keyed randomness is independent of unrelated draw order",()=>{const expected=keyedUnit(42,"case",3,"response");keyedUnit(42,"unrelated");keyedUnit(99,"other");expect(keyedUnit(42,"case",3,"response")).toBe(expected);});
  test("policy protects terminal, disputed, escalated, cooldown, limit, value, and promises",()=>{const base=generatePortfolio({...DEFAULT_CONFIG,caseCount:1}).cases[0];const check=(patch:Partial<SimulationCase>,day=2)=>evaluatePolicy(projectObservable({...base,...patch},day),"SEND_PAYMENT_REMINDER",DEFAULT_CONFIG.policy).rule;expect(check({state:"RECOVERED",outstandingPaise:0})).toBe("TERMINAL_STOP");expect(check({state:"DISPUTED",dispute:true})).toBe("DISPUTE_STOP");expect(check({state:"ESCALATED",escalated:true})).toBe("ESCALATION_STOP");expect(check({lastContactDay:1})).toBe("COOLDOWN");expect(check({contactAttempts:5,lastContactDay:null})).toBe("CONTACT_LIMIT");expect(check({outstandingPaise:3_000_000,lastContactDay:null})).toBe("HIGH_VALUE");expect(check({promises:[{id:"p",createdDay:0,amountPaise:1,dueDay:3,status:"ACTIVE",amountFulfilledPaise:0,paymentIds:[]}],lastContactDay:null})).toBe("PROMISE_PROTECTION");expect(check({lastContactDay:0},2)).toBeUndefined();});
  test("payments, promises, disputes, stops, and metrics remain reconciled",()=>{const result=runSimulation({caseCount:120,days:30,seed:42});expect(result.metrics.reconciliation.valid).toBe(true);expect(result.metrics.recovery.totalRecoveredPaise).toBeLessThanOrEqual(result.metrics.portfolio.totalStartingOutstandingPaise);for(const c of result.finalCases){expect(c.outstandingPaise).toBeGreaterThanOrEqual(0);expect(c.outstandingPaise+c.recoveredPaise).toBe(c.originalAmountPaise);if(c.state==="RECOVERED")expect(c.outstandingPaise).toBe(0);if(["DISPUTED","ESCALATED","CLOSED","RECOVERED"].includes(c.state)){const terminal=result.auditEvents.findIndex(e=>e.caseId===c.id&&["DISPUTE_DETECTED","CASE_ESCALATED","CASE_CLOSED","CASE_RECOVERED"].includes(e.type));if(terminal>=0)expect(result.auditEvents.slice(terminal+1).filter(e=>e.caseId===c.id&&e.type==="CUSTOMER_CONTACTED")).toHaveLength(0);}}expect(new Set(result.payments.map(p=>p.eventId)).size).toBe(result.payments.length);expect(new Set(result.payments.map(p=>p.paymentId)).size).toBe(result.payments.length);});
});
