import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { EvidenceBadge } from "@/components/app/evidence-badge";
import type { RecoveryDashboardData } from "@/lib/recovery-dashboard-types";

export function EvidenceBoundary({ data }: { data: RecoveryDashboardData }) {
  return <section id="evidence" className="border-t pt-8"><div><p className="text-xs font-medium text-primary">Evidence lab</p><h2 className="mt-2 text-2xl font-semibold tracking-[-0.03em]">What this screen proves</h2><p className="mt-2 text-sm text-muted-foreground">Four evidence classes remain separate from input through headline metric.</p></div>
    <div className="mt-6 grid gap-6 border-y py-6 sm:grid-cols-2 lg:grid-cols-4"><div><EvidenceBadge kind="synthetic">Synthetic receivables</EvidenceBadge><p className="mt-2 text-xs leading-5 text-muted-foreground">Controlled invoice values, aging, histories, and capacity constraints.</p></div><div><EvidenceBadge kind="measured">Measured decisions</EvidenceBadge><p className="mt-2 text-xs leading-5 text-muted-foreground">Proposals, policy outcomes, allocation, and deterministic hashes.</p></div><div><EvidenceBadge kind="simulated">Simulated outcomes</EvidenceBadge><p className="mt-2 text-xs leading-5 text-muted-foreground">Customer response and payment behavior under disclosed assumptions.</p></div><div><EvidenceBadge kind="test">Razorpay not invoked</EvidenceBadge><p className="mt-2 text-xs leading-5 text-muted-foreground">Test Mode collection is a separate integration proof.</p></div></div>
    <div className="mt-4 grid gap-3 md:grid-cols-2"><Collapsible><CollapsibleTrigger className="w-full rounded-lg border bg-card px-4 py-3 text-left text-sm font-medium">Metric definitions and limitations</CollapsibleTrigger><CollapsibleContent className="px-4 py-3 text-xs leading-5 text-muted-foreground"><p>Simulated recovery is starting outstanding minus ending outstanding. Paired difference compares Recoup with native reminders on the same synthetic portfolio and outcome bank.</p><ul className="mt-2 list-disc pl-4"><li>No real receivables or Live Mode money appear here.</li><li>Scenario probabilities are assumptions, not calibrated predictions.</li><li>Three development seeds do not establish significance or causal uplift.</li></ul></CollapsibleContent></Collapsible><Collapsible><CollapsibleTrigger className="w-full rounded-lg border bg-card px-4 py-3 text-left text-sm font-medium">Reproducibility hashes</CollapsibleTrigger><CollapsibleContent className="grid gap-2 px-4 py-3 text-xs"><code className="break-all">Decision cache · {data.evidence.decisionCacheHash}</code><code className="break-all">Outcome bank · {data.evidence.outcomeBankHash}</code><span className="text-muted-foreground">Scenario {data.evidence.scenarioVersion} · seeds {data.developmentRange.seeds.join(", ")}</span></CollapsibleContent></Collapsible></div>
  </section>;
}
