import type { RecoveryCaseSnapshot } from "@/lib/recovery";
import type { Replay } from "@/components/collection/types";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { EvidenceBadge } from "@/components/app/evidence-badge";
import { formatMoney } from "@/components/app/money-value";

export function PromiseAndQueueImpact({ recoveryCase, replay }: { recoveryCase: RecoveryCaseSnapshot; replay: Replay | null }) {
  const promise = replay?.promises.findLast((item) => item.status !== "CANCELLED") ?? null;
  return <section data-testid="promise-queue-impact" className="grid gap-4 lg:grid-cols-2"><Card className="shadow-none"><CardHeader><p className="text-xs font-medium text-primary">05 · Promise protection</p><CardTitle>{promise?.status === "ACTIVE" ? `${formatMoney(promise.amountPaise ?? 0)} protected` : recoveryCase.status === "RECOVERED" ? "No remainder outstanding" : "Waiting for verified ₹40,000"}</CardTitle></CardHeader><CardContent><p className="text-xs leading-5 text-muted-foreground">{promise?.status === "ACTIVE" ? `Authoritative application arithmetic activated the remainder through ${promise.promisedDate}.` : recoveryCase.status === "RECOVERED" ? "Verified cumulative payment closed this case; no new promise is inferred." : "The model’s remainder is pending; it is not authoritative until the exact verified partial payment arrives."}</p><EvidenceBadge kind={promise?.status === "ACTIVE" || recoveryCase.status === "RECOVERED" ? "verified" : "measured"} className="mt-4">{promise?.status === "ACTIVE" || recoveryCase.status === "RECOVERED" ? "VERIFIED TEST WEBHOOK" : "NO PAYMENT CLAIM"}</EvidenceBadge></CardContent></Card><Card className="shadow-none"><CardHeader><p className="text-xs font-medium text-primary">06 · Operational queue</p><CardTitle>Freed capacity moves</CardTitle></CardHeader><CardContent><div className="divide-y rounded-lg border">{replay?.queue.map((item) => <div key={item.id} className={`flex items-center justify-between gap-3 p-3 text-xs ${item.id === recoveryCase.id ? "bg-muted" : ""}`}><span><strong className="block">{item.invoiceNumber}</strong><small className="text-muted-foreground">{item.customerName}</small></span><strong>{item.queueStatus.replaceAll("_", " ")}</strong></div>)}</div><p className="mt-3 text-[11px] text-muted-foreground">Operational Test Mode queue · separate from the synthetic Recovery Frontier.</p></CardContent></Card></section>;
}
