import type { CommitmentProposal } from "@/lib/commitment-interpreter";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { EvidenceBadge } from "@/components/app/evidence-badge";
import { formatMoney } from "@/components/app/money-value";

function Evidence({ proposal, message }: { proposal: CommitmentProposal; message: string }) {
  return <div className="mt-5 grid gap-2">{proposal.evidence.map((item,index) => <div key={`${item.field}-${index}`} className="grid gap-1 rounded-lg border bg-muted/40 p-3 sm:grid-cols-[130px_1fr_auto] sm:items-center"><span className="text-[10px] font-medium uppercase tracking-wide text-muted-foreground">{item.field.replaceAll("_", " ")}</span><q className="text-xs">{message.slice(item.start,item.end)}</q><code className="text-[10px] text-muted-foreground">{item.start}:{item.end}</code></div>)}</div>;
}

type Proposal = { revision: number; source: string; proposalHash: string; proposal: CommitmentProposal };
export function ProposalPanel({ proposal, currentMessage, privacyLabel }: { proposal: Proposal | null; currentMessage: string; privacyLabel: string | null }) {
  const modelLabel = proposal?.source === "CACHED_MODEL" ? "CACHED MODEL REPLAY" : "LIVE MODEL";
  return <Card className="shadow-none"><CardHeader className="border-b"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-medium text-primary">02 · Grounded extraction</p><CardTitle className="mt-1">AI proposal</CardTitle><CardDescription className="mt-1">Validated schema, exact evidence spans, and frozen model provenance.</CardDescription></div>{proposal ? <div className="flex flex-wrap gap-1"><EvidenceBadge kind={proposal.source === "CACHED_MODEL" ? "simulated" : "measured"}>{modelLabel}</EvidenceBadge>{privacyLabel ? <EvidenceBadge kind="measured">{privacyLabel}</EvidenceBadge> : null}</div> : null}</div></CardHeader><CardContent>{proposal ? <><div className="grid gap-4 sm:grid-cols-3"><div><p className="text-xs text-muted-foreground">Intent</p><p className="mt-1 text-sm font-medium">{proposal.proposal.intent.replaceAll("_", " ")}</p></div><div><p className="text-xs text-muted-foreground">Pay now</p><p className="mt-1 text-2xl font-semibold tracking-tight">{proposal.proposal.pay_now_paise ? formatMoney(proposal.proposal.pay_now_paise) : "No amount"}</p></div><div><p className="text-xs text-muted-foreground">Promise / confidence</p><p className="mt-1 text-sm font-medium">{proposal.proposal.promised_date ?? "—"} · {Math.round(proposal.proposal.confidence * 100)}%</p></div></div><Evidence proposal={proposal.proposal} message={currentMessage} /><p className="mt-4 break-all font-mono text-[10px] text-muted-foreground">output {proposal.proposalHash} · revision {proposal.revision}</p></> : <p className="py-8 text-center text-sm text-muted-foreground">Run the interpreter to freeze a validated proposal and its exact evidence spans.</p>}</CardContent></Card>;
}
